# Generated by Django 3.2.25 on 2024-05-10 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('B', 'BUY'), ('S', 'SELL')], max_length=20)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('post_date', models.DateTimeField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_dash.exchanges')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_dash.symbols')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_open', models.FloatField()),
                ('price_close', models.FloatField()),
                ('price_low', models.FloatField()),
                ('price_high', models.FloatField()),
                ('time_open', models.DateTimeField()),
                ('time_close', models.DateTimeField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_dash.exchanges')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_dash.symbols')),
            ],
        ),
    ]
