# Generated by Django 3.2.25 on 2024-05-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiat',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='records',
            name='fiat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crypto_dash.fiat'),
            preserve_default=False,
        ),
    ]
