# Generated by Django 3.2.25 on 2024-05-10 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_dash', '0002_auto_20240510_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crypto_dash.type'),
            preserve_default=False,
        ),
    ]
