# Generated by Django 5.0.4 on 2024-06-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_dash', '0003_records_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='period_end',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='records',
            name='period_start',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='records',
            name='trades',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='records',
            name='volume',
            field=models.FloatField(),
            preserve_default=False,
        ),
    ]
