# Generated by Django 5.0.4 on 2024-06-07 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_dash', '0004_records_period_end_records_period_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='records',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_dash.time'),
            preserve_default=False,
        ),
    ]
